# Generated by Django 3.1.5 on 2021-02-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('vat', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=10)),
                ('Founded_date', models.DateField()),
                ('Postcode', models.IntegerField()),
                ('Address', models.TextField(max_length=40)),
                ('Phone_number', models.IntegerField()),
                ('Website', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('Model', models.TextField()),
                ('Body_color', models.CharField(max_length=10)),
                ('Body_color_original', models.CharField(max_length=10)),
                ('Upholstery', models.CharField(max_length=10)),
                ('Body_type', models.CharField(max_length=10)),
                ('Number_of_doors', models.IntegerField()),
                ('Type', models.CharField(choices=[('1', 'new'), ('2', 'used')], max_length=4)),
                ('Country_version', models.CharField(max_length=10)),
                ('Gearing_type', models.CharField(choices=[('1', 'manual'), ('2', 'automatic')], max_length=9)),
                ('Gears', models.IntegerField()),
                ('Disp_engine_vol_cc', models.IntegerField()),
                ('Horsepower', models.IntegerField()),
                ('Tork', models.IntegerField()),
                ('Km_driven', models.IntegerField()),
                ('Fuel', models.CharField(max_length=10)),
                ('Price', models.IntegerField()),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.seller')),
            ],
        ),
    ]
