# Generated by Django 3.1.5 on 2021-02-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Disp_engine_vol_cc',
            new_name='Disp',
        ),
        migrations.AlterField(
            model_name='car',
            name='Gearing_type',
            field=models.IntegerField(choices=[('1', 'manual'), ('2', 'automatic')], max_length=9),
        ),
        migrations.AlterField(
            model_name='car',
            name='Type',
            field=models.IntegerField(choices=[('1', 'new'), ('2', 'used')], max_length=4),
        ),
    ]
