# Generated by Django 3.1.5 on 2021-02-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_auto_20210202_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Gearing_type',
            field=models.IntegerField(choices=[('1', 'manual'), ('2', 'automatic')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='Type',
            field=models.IntegerField(choices=[('1', 'new'), ('2', 'used')]),
        ),
    ]
