# Generated by Django 3.1.5 on 2021-02-05 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cars', '0004_seller_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='owner_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Cars', to='auth.user'),
            preserve_default=False,
        ),
    ]
