# Generated by Django 3.1.5 on 2021-02-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0005_car_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
