# Generated by Django 3.1.5 on 2021-02-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0007_auto_20210205_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='Seller_id',
        ),
    ]
